### PR TITLE
updated for 2024

### PR DESCRIPTION
**Pull request by TheWarbeast**
Added a missing rescource and a few stations i dont know if the names are the right way around so please check that.

### CODE REVIEW

**Comment by TheWarbeast** [comment]
please update the tool

**Comment by TheWarbeast** [comment]
added station names to both sides

**Comment by AnEmortalKid** [comment]
Thank you for doing this. I’ll check it this evening and confirm , it’s been a while since I touch this so I gotta refesh my memory :) but I appreciate your effort !!

**Comment by AnEmortalKid** [comment]
Alrighty I took a peek and I don't remember how this works much, nor can I run it locally at the moment due to old versions. So it will take me a bit to get that working again and then I can take your change (confirming nothing breaks).

Thanks for fixing things!

**Comment by AnEmortalKid** [comment]
Merged with main

confirm it works, for now we will have outdated locations until they expire probably, which i think is fine

image

**Comment by AnEmortalKid** [comment]
This is now live on the site. Let me know if you run into problems.

Than you once again @TheWarbeast for fixing this up :) I look forward to your updates to it when we get the pyro stations !

**Pull request merged**
