### PR TITLE
add contributing section and nodemon watch

### PR DESCRIPTION
**Pull request by Andrew-Pynch**
I added a new command to your start script 
```
yarn start:watch
```

will automatically rebuild and reserve the application every time changes are made. Should make it way easier for you and others to add changes in the future.

Also wrote a little contributing section. 

Will add the features I had in mind tomorrow :-)

### CODE REVIEW

**Comment by AnEmortalKid** [comment]
Darn, I bet i forgot to set the .gitattributes auto=crlf since I use a windows machine. Mind running the prettier and seeing if that swaps the new lines?

**Comment by Andrew-Pynch** [comment]
I'm on windows too. I'll give it a shot though 🤞

**Comment by Andrew-Pynch** [comment]
@AnEmortalKid  We are good to go!

**Review by AnEmortalKid — APPROVED** [review]

**Comment by AnEmortalKid** [comment]
TYVM!

**Pull request merged**
